services:
  discord-bot:
    container_name: discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    
    volumes:
      - ./data:/app/data
      # ダウンロード中の一時ファイルを確認したい場合のみ、以下のコメントを外してください
      # - ./outputs:/app/outputs