# builder stage
FROM node:22-slim as builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

# runner stage

FROM node:22-slim

WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY --from=builder /app/build ./build

CMD ["npm", "run", "start"]