version: '3.8'
services:
  discord-bot:
    container_name: discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    restart: unless-stopped
    command: bun run start
    network_mode: host